New log file opened at Wed Jan 06 13:33:57 CET 2016 by 12324@LOICK-TOSH
Taking next connection to: 1722
New client attempting to connect on port: 1723-1722
  Address = /192.168.56.1:1722
This client on port 1723 has uuid 354502b4-8376-45d2-94e8-f9c592c581d3 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-354502b4-8376-45d2-94e8-f9c592c581d3
Taking next connection to: 1722
New client attempting to connect on port: 1724-1722
  Address = /192.168.56.1:1722
Handshake exception on socket: 1724
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 1722
New client attempting to connect on port: 1725-1722
  Address = /192.168.56.1:1722
This client on port 1725 has uuid b94c5438-080d-47e4-9851-a35abc36c307 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-354502b4-8376-45d2-94e8-f9c592c581d3, play-fork-run-b94c5438-080d-47e4-9851-a35abc36c307
Taking next connection to: 1722
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 1722
